apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: reencrypt-tls-www
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl.mc-nginx.com
    serverSSL: /Common/serverssl.www.mc-nginx.com
    reference: bigip
  hosts:
  - www.mc-nginx.com

