apiVersion: v1
kind: Service
metadata:
  annotations:
  name: svc-route-a
  namespace: nginx-ingress
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/instance: nginxingress-sample
    app.kubernetes.io/name: nginx-ingress
  sessionAffinity: None
  type: ClusterIP
