apiVersion: v1
kind: Service
metadata:
  annotations:
  name: svc-route-d
  namespace: istio-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: istio-ingressgateway
  type: ClusterIP
