apiVersion: v1
kind: Service
metadata:
  annotations:
  name: svc-route-a
  namespace: istio-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: istio-ingressgateway
  sessionAffinity: None
  type: ClusterIP
