apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: virtualserver-route-b
  namespace: istio-system
  labels:
    f5cr: "true"
spec:
  host: www.mc-istio.com
  ipamLabel: test
  hostGroup: mc-istio.com
  tlsProfileName: reencrypt-tls-www
  pools:
  - path: /shop
    servicePort: 8443
    service: svc-route-b
    monitor:
      type: https
      name: /Common/www.mc-istio.com-shop
      reference: bigip
    extendedServiceReferences:
    - clusterName: ocp3
      namespace: istio-system
      port: 8443
      serviceName: svc-route-b


