apiVersion: v1
kind: Service
metadata:
  name: cis-health-bigip1
  namespace: cis-mc-twotier
  labels:
     app: k8s-bigip1-ctlr-deployment
spec:
  ports:
  - name: cis-health-svc
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  type: NodePort
  selector:
    app: k8s-bigip1-ctlr-deployment

