apiVersion: v1
kind: ConfigMap
metadata:
    name: global-cm
    namespace: cis-sc-twotier
    labels:
        f5nr: "true"
data:
    extendedSpec: |
      baseRouteSpec:
        defaultTLS:
          clientSSL: /Common/clientssl
          serverSSL: /Common/serverssl
          reference: bigip
        autoMonitor: service-endpoint
      extendedRouteSpec:
      - namespace: openshift-ingress
        vserverAddr: 10.1.10.103
        vserverName: sharded
        bigIpPartition: sharded
        allowOverride: true
        policyCR: cis-sc-twotier/policy-default

