apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-d
  namespace: mc-twotier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: route-d
  template:
    metadata:
      labels:
        app: route-d
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift
        env:
        - name: RESPONSE
          value: "Two tier Route D in OCP1: account.mc-nginx.com/"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumemounts:
        - name: tmp
          mountpath: "/tmp"
        terminationmessagepath: "/dev/termination-log"
        imagepullpolicy: ifnotpresent
        securitycontext:
          capabilities: {}
          privileged: false
      volumes:
      - name: tmp
        emptydir: {}
      restartpolicy: always
      dnspolicy: clusterfirst
      Serviceaccount: ''
---
apiVersion: v1
kind: Service
metadata:
  name: route-d
  namespace: mc-twotier
  labels:
    app: route-d
spec:
  ports:
  - name: route-d-svc
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: route-d

