apiVersion: v1
kind: ConfigMap
metadata:
    name: global-cm.ocp2
    namespace: f5bigipctlr
    labels:
        f5nr: "true"
data:
    extendedSpec: |
      mode: active-active
      highAvailabilityCIS:
        primaryEndPoint: http://10.1.10.5:30001/health
        probeInterval: 30
        retryInterval: 3
        primaryCluster:
          clusterName: ocp2
          secret: f5bigipctlr/kubeconfig.ocp2
        secondaryCluster:
          clusterName: ocp1
          secret: f5bigipctlr/kubeconfig.ocp1
      externalClustersConfig:
      - clusterName: ocp3
        secret: f5bigipctlr/kubeconfig.ocp3

