apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: route-b
  namespace: openshift-ingress
  labels:
    f5cr: "true"
spec:
  host: www.sc-twotier.com
  hostGroup: sc-twotier.com
  virtualServerAddress: "10.1.10.104"
  tlsProfileName: reencrypt-tls
  pools:
  - path: /shop
    service: router-default-route-b
    servicePort: 443
    monitor:
      type: https
      name: /Common/www.sc-twotier.com-shop
      reference: bigip
