apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: route-c
  namespace: openshift-ingress
  labels:
    f5cr: "true"
spec:
  host: www.sc-twotier.com
  hostGroup: sc-twotier.com
  virtualServerAddress: "10.1.10.104"
  tlsProfileName: reencrypt-tls
  pools:
  - path: /checkout
    service: router-default-route-c
    servicePort: 443
    monitor:
      type: https
      send: "GET /checkout HTTP/1.1\r\nHost: www.sc-twotier.com\r\nConnection: close\r\n\r\n"
      recv: "^HTTP/1.1 200"
      interval: 5
      timeout: 16

