apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip2-ctlr-deployment
  namespace: cis-mc-twotier
spec:
  # DO NOT INCREASE REPLICA COUNT
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip2-ctlr-deployment
  template:
    metadata:
      labels:
        app: k8s-bigip2-ctlr-deployment
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      containers:
        - name: k8s-bigip-ctlr
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop: ["ALL"]
          #   runAsNonRoot: true
          #   seccompProfile:
          #     type: RuntimeDefault
          # image: quay.io/f5networks/k8s-bigip-ctlr-devel:a5904e200bf11402611448289d6c864fc7427504
          image: quay.io/f5networks/k8s-bigip-ctlr-devel:d3ba34519282070bc0e16778828d6bb28e63304d
          # image: quay.io/f5networks/k8s-bigip-ctlr:2.15.0
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
              "--bigip-username=$(BIGIP_USERNAME)",
              "--bigip-password=$(BIGIP_PASSWORD)",
              "--bigip-url=10.1.1.8",
              "--bigip-partition=mc-twotier",
              "--namespace=openshift-ingress",
              "--namespace=cis-mc-twotier",
              "--pool-member-type=cluster",
              "--static-routing-mode=true",
              "--shared-static-routes=false",
              "--share-nodes=true",
              "--multi-cluster-mode=secondary",
              "--insecure=true",
              "--custom-resource-mode=true",
              "--extended-spec-configmap=cis-mc-twotier/global-cm.bigip2",
              "--ipam=true",
              "--orchestration-cni=ovn-k8s",
              "--as3-validation=true",
              "--log-as3-response=true"
          ]
