apiVersion: v1
kind: ConfigMap
metadata:
    name: global-cm.bigip1
    namespace: cis-mc-twotier
    labels:
        f5nr: "true"
data:
    extendedSpec: |
      mode: active-active
      highAvailabilityCIS:
        primaryEndPoint: http://10.1.10.5:30000/health
        probeInterval: 30
        retryInterval: 3
        primaryCluster:
          clusterName: ocp1
          secret: cis-mc-twotier/kubeconfig.ocp1
          ratio: 1
        secondaryCluster:
          clusterName: ocp2
          secret: cis-mc-twotier/kubeconfig.ocp2
          ratio: 1
      externalClustersConfig:
      - clusterName: ocp3
        secret: cis-mc-twotier/kubeconfig.ocp3
        ratio: 1
