apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipam-nfs
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
  nfs:
    path: /nfs/ipam
    server: 10.1.10.4
    readOnly: false

