apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: reencrypt-tls-www
  namespace: istio-system
  labels:
    f5cr: "true"
spec:
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/www.sc-istio.com
    reference: bigip
  hosts:
  - www.sc-istio.com

