apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: oneconnect-policy
  namespace: openshift-ingress
spec:
  snat: auto
  profiles:
    persistenceProfile: none
    profileMultiplex: /Common/oneconnect
