apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: route-red
  namespace: openshift-ingress
  labels:
    f5cr: "true"
spec:
  host: www.multicluster.com
  ipamLabel: test
  hostGroup: multicluster.com
  tlsProfileName: tls-reencrypt-www
  policyName: oneconnect-policy
  pools:
  - path: /
    service: service-red
    servicePort: 443
    monitor:
      type: https
      name: /Common/www.multicluster.com
      reference: bigip

