apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: route-blue
  namespace: openshift-ingress
  labels:
    f5cr: "true"
spec:
  host: shop.multicluster.com
  ipamLabel: test
  hostGroup: multicluster.com
  tlsProfileName: tls-reencrypt-shop
  policyName: oneconnect-policy
  pools:
  - path: /
    service: service-blue
    servicePort: 443
    monitor:
      type: https
      name: /Common/shop.multicluster.com
      reference: bigip
    extendedServiceReferences:
    - clusterName: ocp3
      namespace: openshift-ingress
      serviceName: service-blue
      port: 443

