apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    f5nr: "true"
    f5type: sharded
  name: shard-d
  namespace: openshift-ingress
spec:
  host: account.sharded.com 
  path: /
  port:
    targetPort: 443
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: router-internal-shard-d
    weight: 100
  wildcardPolicy: None

