apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipam-pvc
  namespace: cis-sc-twotier
spec:
  accessModes:
    - ReadWriteMany
  volumeName: ipam-nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
