apiVersion: v1
kind: Namespace
metadata:
  labels:
    demo: sharded
  name: cis-mc-twotier-bigip1
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: global-cm.bigip1
    namespace: cis-mc-twotier-bigip1
    labels:
        f5nr: "true"
data:
    extendedSpec: |
      mode: ratio
      highAvailabilityCIS:
        primaryEndPoint: http://10.1.10.5:30000/health
        probeInterval: 30
        retryInterval: 3
        primaryCluster:
          clusterName: ocp1
          secret: cis-mc-twotier/kubeconfig.ocp1
          ratio: 1
        secondaryCluster:
          clusterName: ocp2
          secret: cis-mc-twotier/kubeconfig.ocp2
          ratio: 1
      externalClustersConfig:
      - clusterName: ocp3
        secret: cis-mc-twotier/kubeconfig.ocp3
        ratio: 1
      baseRouteSpec:
        defaultTLS:
          clientSSL: /Common/clientssl
          serverSSL: /Common/serverssl
          reference: bigip
        autoMonitor: service-endpoint
      extendedRouteSpec:
      - namespace: openshift-ingress
        vserverAddr: 10.1.10.102
        vserverName: mc-twotier
        bigIpPartition: mc-twotier
        allowOverride: true
        policyCR: cis-mc-twotier/policy-default

