---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app1
  namespace: mc-onetier-eng-caas-guestbook-app1
  labels:
    app: guestbook-app1
    version: "2.0"
spec:
  selector:
    matchLabels:
      app: guestbook-app1
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook-app1
        version: "2.0"
    spec:
      containers:
      - name: guestbook
        image: docker.io/ibmcom/guestbook:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 4
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-app1
  namespace: mc-onetier-eng-caas-guestbook-app1
  labels:
    app: guestbook-app1
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: guestbook-app1
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guestbook-app1
  namespace: mc-onetier-eng-caas-guestbook-app1
  annotations:
    virtual-server.f5.com/clientssl: cafe-tls-secret
  labels:
    app: guestbook-app1
    f5nr: "true"
    f5type: mc-onetier
spec:
  host: guestbook-app1.apps.f5-udf.com
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: guestbook-app1
    weight: 100
  wildcardPolicy: None


