apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: route-c
  namespace: openshift-ingress
  labels:
    f5cr: "true"
spec:
  host: www.sc-twotier.com
  virtualServerAddress: "10.1.10.104"
  tlsProfileName: reencrypt-tls
  pools:
  - path: /checkout
    service: router-shard-apps-route-c
    servicePort: 443
    monitor:
      interval: 5
      recv: ""
      send: /checkout
      timeout: 16
      type: https

