apiVersion: v1
kind: Service
metadata:
  annotations:
  name: router-shard-apps-route-d
  namespace: openshift-ingress
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: shard-apps
  sessionAffinity: None
  type: ClusterIP
