apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: route-d
  namespace: openshift-ingress
  labels:
    f5cr: "true"
spec:
  host: account.migration.com
  virtualServerAddress: "10.1.10.106"
  hostGroup: migration.com
  tlsProfileName: reencrypt-tls
  partition: mc-twotier
  profileMultiplex: "/Common/oneconnect-32"
  pools:
  - path: /
    service: router-default-route-d-ocp1
    servicePort: 443
    weight: 50
    alternateBackends:
    - service: router-default-route-d-ocp2
      weight: 50
    monitor:
      type: https
      name: /Common/account.migration.com
      reference: bigip

