apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: route-a
  namespace: openshift-ingress
  labels:
    f5cr: "true"
spec:
  host: www.migration.com
  virtualServerAddress: "10.1.10.106"
  hostGroup: migration.com
  tlsProfileName: reencrypt-tls
  profileMultiplex: "/Common/oneconnect-32"
  pools:
  - path: /
    service: router-default-route-a-ocp1
    servicePort: 443
    weight: 50
    alternateBackends:
    - service: router-default-route-a-ocp2
      weight: 50
    monitor:
      type: https
      send: "GET / HTTP/1.1\r\nHost: www.migration.com\r\nConnection: close\r\n\r\n"
      recv: "^HTTP/1.1 200"
      interval: 5
      timeout: 16
