apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: route-c
  namespace: openshift-ingress
  labels:
    f5cr: "true"
spec:
  host: www.migration.com
  virtualServerAddress: "10.1.10.106"
  hostGroup: migration.com
  tlsProfileName: reencrypt-tls
  profileMultiplex: "/Common/oneconnect-32"
  pools:
  - path: /checkout
    service: router-default-route-c-ocp1
    servicePort: 443
    weight: 50
    alternateBackends:
    - service: router-default-route-c-ocp2
      weight: 50
    monitor:
      type: https
      name: /Common/www.migration.com-checkout
      reference: bigip
