apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mc-istio-account
  namespace: mc-twotier
spec:
  hosts:
  - account.mc-istio.com
  gateways:
  - mc-istio
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: route-d


